# gcloud container builds submit --config=cloudbuild.yaml .
# 不依赖Cloud Source Repositories
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-jetty:1.0.0', '.']
images:
- 'gcr.io/$PROJECT_ID/my-jetty:1.0.0'
